name: Formatters

on:
  push:
    branches: [ master ]

jobs:
  libraries:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: FormatterLib CMake
      run: |
        cd formatter_lib
        cmake -H. -B_build
        cmake --build _build

    - name: FormatterExLib CMake
      run: |
        cd formatter_lib
        cmake -H. -B_build
        cmake --build _build
        
    - name: SolverLib Cmake
      run: |
        cd solver_lib
        cmake -H. -B_build
        cmake --build _build
        
    - name: HelloWorldApplication CMake
      run: |
        cd hello_world_application
        cmake .
        cmake --build
        
    - name: SolverApplication CMake
      run: |
        cd solver_application
        cmake .
        cmake --build
      
