name: Formatters

on:
  push:
    branches: [ master ]

jobs:
  libraries:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: FormatterLib CMake
      run: |
        cd formatter_lib
        cmake -H. -B_build
        cmake --build _build

    - name: FormatterExLib CMake
      run: |
        cd formatter_lib
        cmake -H. -B_build
        cmake --build _build
        
    - name: SolverLib Cmake
      run: |
        cd solver_lib
        cmake -H. -B_build
        cmake --build _build
        
  Hello_world:
    runs-on: ubuntu-latest
    needs: [ libraries ]
    
    steps:
    - uses: actions/checkout@v2
      
    - name: HelloWorldApplication CMake
      run: |
        mkdir _build
        cd _build
        cmake ..
        cmake --build .
        cd _build/hello_world_application
        ./hello_world
        
  Solver:
    runs-on: ubuntu-latest
    needs: [ libraries ]
    
    steps:
    - uses: actions/checkout@v2
      
    - name: SolverApplication CMake
      run: |
        mkdir _build2
        cd _build2
        cmake ..
        cmake --build .
        cd _build2/solver_application
        ./solve 2 -4 2
      
